### ISSUE TITLE
Date of new release

### ISSUE THREAD

**Issue by aborowiecwsb** [HubSpot/slack-client#140]
Can you tell when are you going to do new release?
Asking about version 1.5

**Comment by Patras3** [comment]
I'm waiting for 1.5 version on maven central also.

**Comment by szabowexler** [comment]
We'll make sure 1.5 is available next week.

**Comment by szabowexler** [comment]
Circling back, looks like we missed a step in our release process, looking to get that fixed (and have 1.5 available on maven central) by tomorrow.

**Comment by szabowexler** [comment]
All set! We jumped 1.5, and released 1.6 (we missed the TTL on our artifact cache, and rather than mess around we just jumped right to 1.6). That should be available on maven central with the latest goodness.
