### ISSUE TITLE
Post message IllegalStateException

### ISSUE THREAD

**Issue by victoriaaa234** [HubSpot/slack-client#147]
I tried to post a message to a private channel (conversation) and set the text, but I get an illegal state exception: 

ERROR com.hubspot.slack.client.interceptors.http.DefaultHttpResponseDebugger: REQ<7> [chat_postMessage]: Failed interaction

IllegalStateException: SlackError{type=UNKNOWN, error=invalid_arguments}
```
{
  "ok" : false,
  "error" : "invalid_arguments",
  "deprecated_argument" : "as_user",
  "warning" : "missing_charset",
  "response_metadata" : {
    "warnings" : [ "missing_charset" ]
  }
}
```
Here is what I tried:

```
Result<ChatPostMessageResponse, SlackError> postResult = slackClient.postMessage(
         ChatPostMessageParams.builder()
                   .setText("hey there")
                   .setChannelId(getChannelId(channelName))
                   .build()
).join();
```

I've also tried passing in the channelName as the slack api suggests and followed the examples in this library but still gave me the same error.

Could anyone please take a look?

**Comment by szabowexler** [comment]
Ahhh lovely. Slack has changed their API on us. -.-

From the `chat.postMessage` docs:

> Please note that the as_user parameter may not be used by new Slack apps. Read more about Authorship to understand how as_user works for classic Slack apps.

Basically for _legacy_ apps (most of our users atm), the [authorship](https://api.slack.com/methods/chat.postMessage#authorship) section applies, and talks about that field. Newer apps can't use it. This means we'll need to change the params to enable new apps to use the client.

I'll prioritize getting that out, though the timing is painful since we _just_ cut 1.6, and unless you're on 1.7-SNAPSHOT you won't get this until we release 1.7.

**Comment by victoriaaa234** [comment]
@szabowexler I just patched up the new release 1.7-SNAPSHOT, but unfortunately i still get this error :( not sure how to proceed. could you please take a look? It's the same code as I wrote previously ^

```
{
  "ok" : false,
  "error" : "invalid_arguments",
  "deprecated_argument" : "as_user",
  "warning" : "missing_charset",
  "response_metadata" : {
    "warnings" : [ "missing_charset" ]
  }
}
```

**Comment by hikuley** [comment]
I'm getting same error like below error.

**Comment by ng683728** [comment]
Same here :-(

**Comment by BobbyJohansen** [comment]
I think the problem lies here https://github.com/HubSpot/slack-client/blob/19bb9525266a376d27f2abe332a40cc89e200e71/slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/AbstractChatMessageParams.java#L21 where the non absent might be taking the optional as not null

**Comment by nikoe14** [comment]
Hey guys, facing the same issue here 😭  and :sad_panda:

**Comment by szabowexler** [comment]
Hey everyone - sorry for our absence, things have been pretty hectic over the recent few months, and I do apologize.

Can folks still encountering this do me a favor, and just chime in with which version of the client you're seeing it on?
