### ISSUE TITLE
Authorization token query parameter is no longer supported for new Slack apps

### ISSUE THREAD

**Issue by b-reynolds** [HubSpot/slack-client#215]
The Slack API no longer supports the authorization token query parameter for bots created since the 24th Februrary (https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps).

This project seems to still use this query parameter which is causing requests such as `conversations.list` to fail with an `invalid_auth` error.

I've only just found the cause of the issue but can't see an obvious way of configuring how the token is sent in a request using the `SlackClientRuntimeConfig`.

**Comment by tpoll** [comment]
I believe https://github.com/HubSpot/slack-client/pull/222 should fix your issue.
