### ISSUE TITLE
CI checks are falling

### ISSUE THREAD

**Issue by leonidhladii** [HubSpot/slack-client#218]
**Describe the bug**
Need to investigate and fix why all new PR checks are falling - 
`Caused by: java.lang.RuntimeException: Unable to find commits until some tag`,
`Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 8805e826b967b08812a4bb13d80ddfe1eca9f98b`

**To Reproduce**
1. Create a new PR (or open existsed)
2. Go to Checks section
3. Open any of failed CI build details

**Expected behavior**
New PR checks should be successful

**Comment by jaredstehler** [comment]
PR checks are working now
