### ISSUE TITLE
ts is required by SlackEvent model, but Slack does not set ts on all events

### ISSUE THREAD

**Issue by BWehner** [HubSpot/slack-client#52]
**Describe the bug**
`ts` is required by the SlackEvent interface, but slack only sets `ts` on some events, such as messages sent, while not on others, such as channel_created

**To Reproduce**
Try to parse a channel_created to a SlackEvent

**Expected behavior**
All slack events JSON should be parseable to SlackEvent

**Additional context**
**Note: Fixing this would be a breaking change, as it would change the SlackEvent interface**
_Edit: Actually, this could be fixed in a non-breaking way by making ts nullable, which would be uglier but would fix this bug_ 
See: https://api.slack.com/events-api#event_type_structure
https://api.slack.com/events/channel_created
https://api.slack.com/events/message (which DOES include ts)

Example channel_created message:
```
{
  "token": "uWopedqK86MJfjUeq8v9pUAD",
  "team_id": "TBQPW3FH6",
  "api_app_id": "A945JNH24",
  "event": {
    "type": "channel_created",
    "channel": {
      "id": "CCXF9BDV1",
      "is_channel": true,
      "name": "test",
      "name_normalized": "test",
      "created": 1537452804,
      "creator": "UBRFHDFGA",
      "is_shared": false,
      "is_org_shared": false
    },
    "event_ts": "1537452804.000100"
  },
  "type": "event_callback",
  "event_id": "EvCXCPK952",
  "event_time": 1537452804,
  "authed_users": [
    "UBRFHDFGA"
  ]
}
```

**Comment by szabowexler** [comment]
This is pretty dangerous. In general, the way to handle this is to change the way it's set up by adding an optional version, migrating usages onto that, and going forward from there. We don't generally want to return `null` to get around this, because while it may not break the API, it violates the invariant that any non-optional return is also non-null.

**Comment by darcatron** [comment]
> adding an optional version

Do you mean to add _another_ field that has an optional timestamp? AFAIK, deserialization can only map a key to a single field. So the new optional field would have to be `Derived` and then later updated once usages are migrated. Is that what you mean?

**Comment by szabowexler** [comment]
Yeah exactly.
