### ISSUE TITLE
Allow custom rate limiters on SlackClient

### ISSUE THREAD

**Issue by BWehner** [HubSpot/slack-client#57]
Currently, SlackClient only rate limits on method, not the method-token combination that Slack actually rate limits apps on. To fix this, we'd like to be able to supply an optional RateLimiter via SlackRuntimeConfig with some well defined interface, and, if supplied, use that rate limiter in SlackClient rather than the static one (i.e. RATE_LIMITERS). Elias has also suggested we cut a release on this feature

**Comment by darcatron** [comment]
This is out now! Thanks @BWehner!
