### ISSUE TITLE
slackClient.channelHistory(ChannelsHistoryParams.builder().setCount(count) is not working

### ISSUE THREAD

**Issue by sselman0** [HubSpot/slack-client#77]
I noticed that setting the count for method above, does not do anything, it always gets all the messages. not sure why this is happening. Using version 1.1

**Comment by szabowexler** [comment]
Sorry for the late response! If this is still an active issue, can you post a snippet of code you're running, the result you expect, and what you're actually seeing?

**Comment by szabowexler** [comment]
I'm going to close this since we didn't get a response, and the reported version (1.1) is fairly behind the most recent (1.4, with 1.5 coming out shortly).
