### ISSUE TITLE
This project is way too complicated. Can you include a plain Java hello world without all the annotations and injection?

### ISSUE THREAD

**Issue by jackmahoney** [HubSpot/slack-client#83]
Factories, factories, factories. This project is so complicated. I gave up trying after looking at the source code and trying to get this to work in a plain Java environment without Guice or DI. Please consider including a simple HelloWorld that posts to a slack channel.

**Comment by latos** [comment]
There's nothing wrong with Guice itself, but a well designed library should't impose it (or its own http client) on other developers.

It would be better to have a pure library that just contains the code, with examples for wiring it up manually.  Separately, a library containing a Guice module can be provided for the convenience of those who are using Guice in their projects.  (DI libraries in general make sense as top level choices for applications, they shouldn't be imposed from the bottom up from "leaf" libraries).

**Comment by namedgraph** [comment]
My thoughts exactly. Take a look at google-api-java-client for a simple design.

**Comment by abhidemon** [comment]
This is the reason why this project could have 100 stars by now, is stuck at 40.

**Comment by kmclarnon** [comment]
This is now available in [Release 1.2](https://github.com/HubSpot/slack-client/releases/tag/1.2)

**Comment by kennycason** [comment]
I know this is old, but I'd also like to see an example in the README for how to configure this without Guice. Of course, I'm going to just dig through all the stuff that is configured by Guice to see how it's supposed to be configured. But after 15 min of looking I still don't have a clear way on a clean/easy way to instantiate things. 

I'd expect something simple like:
```kotlin
val slackClient = SlackWebClient(config);
```
