### ISSUE TITLE
Support for new Layout (Block Kit Builder friendly)

### ISSUE THREAD

**Issue by UncleFirefox** [HubSpot/slack-client#89]
**Is your feature request related to a problem? Please describe.**
Slack released a new way of building messages. As far as I know this library does not support it yet, or am I wrong?

**Describe the solution you'd like**
Have a builder patter the same way we have it now with ChatPostMessageParams.builder which contemplates the new format (maybe a new type?)

**Describe alternatives you've considered**
Doing all the communication using a simple RestTemplate but I think this library is too good not to have the new layout. https://github.com/seratch/jslack might the option to to go

**Additional context**
Library now supports this: https://api.slack.com/docs/messages/builder
And should be able to support this: https://api.slack.com/tools/block-kit-builder

**Comment by santam85** [comment]
This refers to the disclaimer at the top of https://api.slack.com/docs/message-attachments
In short, Attachements might get deprecated shortly in favor of blocks, which offer a much larger set of option to format messages.

**Comment by UncleFirefox** [comment]
I think I might have to move to https://github.com/seratch/jslack for my project if this does not change soon.

**Comment by johnnyleitrim** [comment]
Hi @UncleFirefox - We're starting to add support for Block Kit to our client at the moment.  You can try out the current development version by checking out the `block-kit` branch and building the library.

Most of the `...MessageParams` classes now have a `setBlocks(List<Block>)` method that you can use to add blocks to your messages

**Please note that this is still a work in progress, so the block kit elements may change or be removed.**

**Comment by johnnyleitrim** [comment]
Version 1.4 has been released, which contains Block Kit support.
